version: '3'
services:
  booking:
    container_name: booking_container
    build: .
    depends_on:
      - 'postgres'
    environment:
      PORT: 8080
      NODE_ENV: production
      POSTGRES_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - .:/src/app
  postgres:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
      - webnet
      
volumes:
  pgdata:
networks:
  webnet: