version: '3'

services:

  booking:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'
    environment:
      PORT: 8080
      NODE_ENV: production
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dannywelstad
      POSTGRES_DB: booking

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dannywelstad
      POSTGRES_DB: booking
      